### PR TITLE
Updated to @codingame/monaco-vscode-api@1.85.5

### PR DESCRIPTION
**Pull request by kaisalmen**
~~@CGNonofr `initialize` is broken. I checked your demo differences between `1.85.0` and `1.85.3` there was no code change required. It should just work with the newer version, right or did I miss something?~~
Version `1.85.4` fixes the issue.

The latest version `1.85.5` is now used. In addition this adds a docker-compose based wrapper for the new groovy language server. README is updated.

### CODE REVIEW

**Comment by CGNonofr** [comment]
Yes, you've approved the fix 2 hours ago!

I'll trigger a release

**Comment by kaisalmen** [comment]
@CGNonofr I should have checked the issue. It states the same problem. 🙈 Thank you!

**Comment by kaisalmen** [comment]
@CGNonofr this is ready now.

**Review by CGNonofr — APPROVED** [review]
LGTM

**Comment by kaisalmen** [comment]
@CGNonofr what do you think about the docker-compose approach for the groovy LS?

**Comment by CGNonofr** [comment]
> @CGNonofr what do you think about the docker-compose approach for the groovy LS?

It's maybe a little overkill for a single container but hey at least it's easy to use and there's nothing to configure! (I haven't played with it yet though)

**Comment by kaisalmen** [comment]
> and there's nothing to configure!

That is the point! 😎 The non-container way is described in the README.

**Pull request merged**
