### PR TITLE
handle undefined values

### LINKED ISSUE #154: Cannot read property 'map' of undefined in ProtocolToMonacoConverter.asCodeActions
When try to run version 0.9.0 with different language server (https://github.com/sumneko/lua-language-server), in browser console is error because ProtocolToMonacoConverter.asCodeActions parameter **actions** has undefined value.

### PR DESCRIPTION
**Pull request by akosyakov**
fix #154 - Since Monaco 0.17 can handle undefined values, converters are adjuster to propagate them directly to Monaco.

### CODE REVIEW

**Comment by akosyakov** [comment]
@ph-fuergy Does it resolves https://github.com/TypeFox/monaco-languageclient/issues/154 for you?

**Comment by akosyakov** [comment]
It's published under `dev` tag for testing.

**Comment by akosyakov** [comment]
@rcjsuen Could you have a look please?

**Comment by ph-fuergy** [comment]
> @rcjsuen Could you have a look please?

Yes. I try it with monaco-editor 0.17 and it works.

**Comment by akosyakov** [comment]
@ph-fuergy thanks for checking, merging

**Pull request merged**
