### PR TITLE
Bump the version to 0.14.0

### PR DESCRIPTION
**Pull request by katspaugh**
Additional steps that will be needed after merging this:

Switch to master:
```
git checkout master
git fetch --all; git reset --hard origin/master
```

Create a new tag and push it:
```
git tag '0.14.0'
git push --tags
```

Publish to NPM:
```
npm publish
```

Publish to Lerna:
```
lerna publish
```

### CODE REVIEW

**Comment by CGNonofr** [comment]
LGTM (I'm not an reviewer)

How will it be for the next version, will I be able to publish it? Should I still ping you?

**Comment by katspaugh** [comment]
Thanks!
AFAIU, only the owner of the package can publish it on npm.

**Comment by katspaugh** [comment]
@akosyakov any chance you could merge this?

**Comment by RomanNikitenko** [comment]
@katspaugh 
There is a comment from Anton that 
> Existing committers with merge rights interested in new PRs please feel free to merge them

https://github.com/TypeFox/monaco-languageclient/issues/164#issuecomment-668046916

**Comment by katspaugh** [comment]
Oh, I see. There's [an automation via Travis](https://github.com/TypeFox/monaco-languageclient/blob/master/.travis.yml) that publishes the next version on each push to master.

It would be still nice to release a stable version so that we don't get unexpected updated in the `@next` package.

**Pull request closed without merging**
