### PR TITLE
Update to monaco-vscode-api@1.85.0 and monaco-editor@0.45.0

### PR DESCRIPTION
**Pull request by kaisalmen**
@CGNonofr there are suddenly problems:
This is an error with unchanged code in the JSON client example
image
This one seems to come from `WorkbenchContextKeysHandler`:  
image

I see initialization errors with `IExtensionService` in the Statemachine Example as well.

### CODE REVIEW

**Comment by CGNonofr** [comment]
Can you give it another try with the `1.85.0-next.1` ?

**Comment by kaisalmen** [comment]
@CGNonofr building and testing in a bit. I will let you know soon

**Comment by kaisalmen** [comment]
@CGNonofr looking good. I will release a next version now and do some further tests.

**Comment by kaisalmen** [comment]
@CGNonofr I found another issue:
`createConfiguredDiffEditor` does no longer work

**Comment by kaisalmen** [comment]
I tested it with the examples in `monaco-editor-wrapper` and it is that function call leading to this:
image

**Comment by kaisalmen** [comment]
@CGNonofr looking good now.

**Comment by kaisalmen** [comment]
@CGNonofr This is ready for merge. I already performed the release preparations.

**Review by CGNonofr — APPROVED** [review]
LGTM

**Pull request merged**
