### PR TITLE
All monaco-vscode packages are peerDependencies

### LINKED ISSUE #789: Better peer dependency enforcement needed
The compatibility table is nice, but does not protect people from running into mismatching dependencies.
We should find a technical solution enforcing correct dependencies or warn about wrong ones.

### PR DESCRIPTION
**Pull request by kaisalmen**
This fixes #789 and is related to https://github.com/CodinGame/monaco-vscode-api/issues/544

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr the approach works with npm, pnpm and yarn.

**Comment by cdietrich** [comment]
is there a list of dependencies we need now to prodivde?

**Comment by kaisalmen** [comment]
@cdietrich no, there should be no change on your end needed, but if you have an incompatible monaco-vscode package it will now flag this during install. Depending on the default setting of the package manager the install will fail immediately (npm) or a warning is written (pnpm).

**Comment by kaisalmen** [comment]
@CGNonofr if you agree with this I will perform the final release of the packages (finally 😆) later today or tomorrow.

**Comment by cdietrich** [comment]
hmmm
i had to add more in order for it to work

```
   "dependencies": {
+    "@codingame/monaco-vscode-api": "~11.1.2",
+    "@codingame/monaco-vscode-configuration-service-override": "~11.1.2",
+    "@codingame/monaco-vscode-editor-api": "~11.1.2",
+    "@codingame/monaco-vscode-extensions-service-override": "~11.1.2",
     "@codingame/monaco-vscode-keybindings-service-override": "~11.1.2",
+    "@codingame/monaco-vscode-languages-service-override": "~11.1.2",
+    "@codingame/monaco-vscode-localization-service-override": "~11.1.2",
+    "@codingame/monaco-vscode-log-service-override": "~11.1.2",
+    "@codingame/monaco-vscode-model-service-override": "~11.1.2",
-    "monaco-editor-wrapper": "6.0.0-next.11",
-    "monaco-languageclient": "9.0.0-next.11",
-    "vscode-ws-jsonrpc": "^3.3.2"
+    "monaco-editor-wrapper": "6.0.0-next.14",
+    "monaco-languageclient": "9.0.0-next.14",
+    "vscode-ws-jsonrpc": "3.4.0-next.14"
   },
```

**Comment by kaisalmen** [comment]
@cdietrich this verification example https://github.com/TypeFox/monaco-languageclient/blob/issue-789/verify/peer/package.json will fail with npm

**Review by CGNonofr — APPROVED** [review]
:+1:

**Comment by cdietrich** [comment]
we are using yarn.

with

```
  "dependencies": {
    "@codingame/monaco-vscode-keybindings-service-override": "~11.1.2",
    "monaco-editor-wrapper": "6.0.0-next.14",
    "monaco-languageclient": "9.0.0-next.14",
    "vscode-ws-jsonrpc": "3.4.0-next.14"
  },
```

yarn will complain about missing peers

but at runtime it will fail with e.g.

```
✘ [ERROR] Could not resolve "@codingame/monaco-vscode-languages-service-override"

    ../../node_modules/monaco-languageclient/lib/vscode/services.js:8:40:
      8 │ import getLanguagesServiceOverride from '@codingame/monaco-vscode-languages-service-override';
```

**Comment by cdietrich** [comment]
so i added all of these

**Comment by kaisalmen** [comment]
@cdietrich yes, yarn needs more (it used to be like that before) it does not automatically install required peers (npm and pnpm do). Had to do the same:  https://github.com/TypeFox/monaco-languageclient/blob/main/verify/yarn/package.json

Even with latest yarn there is not argument available that allows to install peer dependencies directly. Don't ask me why.🤷‍♂️

**Comment by kaisalmen** [comment]
@CGNonofr figuring this out was time-consuming (more than I expected). I don't know how many times I installed packages today.

**Comment by kaisalmen** [comment]
@CGNonofr and @cdietrich final version are released:
https://www.npmjs.com/package/monaco-languageclient/v9.0.0
https://www.npmjs.com/package/vscode-ws-jsonrpc/v/3.4.0
https://www.npmjs.com/package/monaco-editor-wrapper/v/6.0.0
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/6.0.0

**Comment by kaisalmen** [comment]
@CGNonofr one very important thing to note here. The peerDependencies work nicely with released packages available via npm. The enforcement does not work inside a workspace. I had a wrong devDependency defined in `monaco-editor-wrapper` and it did not lead to errors (see https://github.com/TypeFox/monaco-languageclient/commit/12bcdf92ffbdd63dc62e793a9385395e4e7f4ee0). Fortunately it was only a devDependency and therefore did not require to updated the released version. Btw, that's also the reason why I released multiple next releases yesterday, becaus only then I was able to tell am approach works for real.

**Pull request merged**
