### PR TITLE
Bump Monaco to 0.19.3

### PR DESCRIPTION
**Pull request by Twinside**
A new enum has been added to the vscode compatibility layer (as
vscode-languageserver rely on it). Also the severity enum converter
use an internal version of the enum to avoid relying on the vscode
module.

Note: I've tried to create the pull request yesterday several times, to no avail.

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
@Twinside 
thank you for the contribution!

I tried to build your changes but got the errors:
```
node-example: src/client.ts(66,57): error TS2345: Argument of type 'import("/home/rnikitenko/project/monaco-languageclient/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/main").MessageConnection' is not assignable to parameter of type 'import("/home/rnikitenko/project/monaco-languageclient/node_modules/vscode-jsonrpc/lib/main").MessageConnection'.
node-example:   Type 'MessageConnection' is missing the following properties from type 'MessageConnection': onProgress, sendProgress, onUnhandledProgress
node-example: src/json-server.ts(7,8): error TS2613: Module '"/home/rnikitenko/project/monaco-languageclient/example/node_modules/vscode-uri/lib/umd/index"' has no default export. Did you mean to use 'import { URI } from "/home/rnikitenko/project/monaco-languageclient/example/node_modules/vscode-uri/lib/umd/index"' instead?
node-example: src/json-server.ts(12,24): error TS2305: Module '"../../node_modules/vscode-languageserver-types/lib/umd/main"' has no exported member 'DocumentSymbolParams'.
node-example: src/json-server.ts(28,36): error TS2554: Expected 1 arguments, but got 0.
node-example: src/json-server.ts(40,43): error TS7006: Parameter 'change' implicitly has an 'any' type.
node-example: src/json-server.ts(43,35): error TS7006: Parameter 'event' implicitly has an 'any' type.
node-example: error Command failed with exit code 2.
```
Looks like the ci-build displays the same.

**Comment by Twinside** [comment]
I'll look at that, I've mainly been interested by making the client work

**Comment by RomanNikitenko** [comment]
@Twinside 
The errors related to `src/json-server.ts` was fixed within https://github.com/TypeFox/monaco-languageclient/pull/197

**Comment by RomanNikitenko** [comment]
I created the branch based on @Twinside fork and tried to fix the compilation errors.
You can see my changes [here](https://github.com/TypeFox/monaco-languageclient/commit/56b6d5d82f3b1d33ea2eeed51204fa9f9c154d05).

I'm new to it, @Twinside could you take a look?

**Pull request closed without merging**
