### PR TITLE
Create a browser example that only relies on HTML and JavaScript

### PR DESCRIPTION
**Pull request by rcjsuen**
I've added a new `/examples/browser/` example that only uses the Monaco converters to get the JSON language service working with a Monaco Editor. This new example does not rely on Express to serve any content via Node.js. You simply build the example with `npm install` and `npm run build` and then open up `/examples/browser/lib/index.html` with a browser and the Monaco Editor should be up and running with JSON support.

The original example has been moved from `/example/` to `/examples/nodejs/`. I have also updated the README.md file to mention the new example.

### CODE REVIEW

**Comment by rcjsuen** [comment]
@akosyakov Thanks for taking a look. I've made some tweaks and force pushed my branch.

**Comment by akosyakov** [comment]
@rcjsuen will you rebase it after merging https://github.com/TypeFox/monaco-languageclient/pull/63?

**Comment by rcjsuen** [comment]
@akosyakov I've made the necessary changes and force pushed my branch.

**Comment by akosyakov** [comment]
@rcjsuen sorry, you will need to rebase it again

**Comment by rcjsuen** [comment]
@akosyakov It happens. I've force pushed again.

**Comment by akosyakov** [comment]
I think we should keep the original example as it is, otherwise, all links in this article will be broken:
http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor

**Comment by akosyakov** [comment]
I see a lot of warnings from the webpack, is there a way to get rid of them? like:
```
WARNING in ./node_modules/vscode-json-languageservice/lib/esm/services/jsonHover.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'jsonHover.js.map': Error: Can't resolve './jsonHover.js.map' in '/workspace/monaco-languageclient/examples/browser/node_modules/vscode-json-languageservice/lib/esm/services'
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js 8:0-49
 @ ./lib/client.js
 @ ./lib/main.js

WARNING in ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'jsonLanguageService.js.map': Error: Can't resolve './jsonLanguageService.js.map' in '/workspace/monaco-languageclient/examples/browser/node_modules/vscode-json-languageservice/lib/esm'
 @ ./lib/client.js 7:36-74
 @ ./lib/main.js

WARNING in ./node_modules/vscode-json-languageservice/lib/esm/parser/jsonParser.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'jsonParser.js.map': Error: Can't resolve './jsonParser.js.map' in '/workspace/monaco-languageclient/examples/browser/node_modules/vscode-json-languageservice/lib/esm/parser'
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js 11:0-57
 @ ./lib/client.js
 @ ./lib/main.js
```

**Comment by rcjsuen** [comment]
I got rid of some of them but there are still a few that eludes me at the moment.
```
WARNING in ./node_modules/vscode-nls/lib/main.js
207:19-66 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/vscode-nls/lib/main.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
 @ ./lib/client.js
 @ ./lib/main.js

WARNING in ./node_modules/vscode-nls/lib/main.js
220:23-52 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/vscode-nls/lib/main.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
 @ ./lib/client.js
 @ ./lib/main.js

WARNING in ./node_modules/vscode-nls/lib/main.js
221:19-72 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/vscode-nls/lib/main.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
 @ ./lib/client.js
 @ ./lib/main.js

WARNING in ./node_modules/vscode-nls/lib/main.js
310:23-41 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/vscode-nls/lib/main.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
 @ ./lib/client.js
 @ ./lib/main.js

WARNING in ./node_modules/vscode-nls/lib/main.js
394:23-53 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/vscode-nls/lib/main.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
 @ ./lib/client.js
 @ ./lib/main.js

WARNING in ./node_modules/vscode-nls/lib/main.js
57:49-88 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/vscode-nls/lib/main.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js
 @ ./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js
 @ ./lib/client.js
 @ ./lib/main.js
```

**Comment by rcjsuen** [comment]
@akosyakov I've force pushed my branch again. There shouldn't be anymore warnings.

**Comment by akosyakov** [comment]
@rcjsuen I think we should keep the original example where it was before. It is referenced from different issues and particularly in this article: http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor Moving it breaks links. Could you move `examles/nodejs` to`example`? For new examples, we will use `examples` folder.

Also, it seems that rebase went wrong a bit, i have both `example` and `examles/nodejs`.
screen shot 2018-03-25 at 10 14 55

**Comment by rcjsuen** [comment]
You're right, I missed some files. Sorry about that. Anyway, I'll make the changes you suggested and then push again. Thanks for reviewing!

**Comment by rcjsuen** [comment]
@akosyakov I've changed it so that the Node.js example stays in `example` and the browser example is in `examples/browser`.

**Comment by rcjsuen** [comment]
Thanks for the review, Anton!

**Pull request merged**
