### PR TITLE
DRAFT -  Update Language Client to 6.0.0

### PR DESCRIPTION
**Pull request by apupier**
- requires upgrade of TtypeScript to 3.7.5 to avoid `error TS1086: An
accessor cannot be declared in an ambient context.`
- requires API updates:
  - client/src/monaco-language-client.ts createMessageTransports now
using Promise instead of Thenable
  - vscode-uri Uri has been renamed URI
  - registerCallHierarchyProvider has moved from workspace to languages

remaining (but didn't grok what it means, I'm a newbie in typescript):
```
monaco-languageclient: src/vscode-api.ts(209,17): error TS2322: Type
'(arg0: Uri, arg1: readonly Diagnostic[] | undefined) => void' is not
assignable to type '{ (uri: Uri, diagnostics: readonly Diagnostic[] |
undefined): void; (entries: readonly [Uri, readonly Diagnostic[] |
undefined][]): void; }'.
```

EDIT:
fixed:
```
monaco-languageclient: src/vscode-api.ts(52,11): error TS2740: Type '{
createFileSystemWatcher(globPattern: GlobPattern, ignoreCreateEvents:
boolean | undefined, ignoreChangeEvents: boolean | undefined,
ignoreDeleteEvents: boolean | undefined): FileSystemWatcher; ... 21 more
...; name: undefined; }' is missing the following properties from type
'typeof workspace': fs, workspaceFile, onWillCreateFiles,
onDidCreateFiles, and 4 more.
```

### CODE REVIEW

**Comment by apupier** [comment]
hum in fact, seems that compilation errro are nto all reported when there is a previous one, here is a bunch of other:

```
node-example: src/client.ts(66,57): error TS2345: Argument of type 'import("/home/apupier/git/monaco-languageclient/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/main").MessageConnection' is not assignable to parameter of type 'import("/home/apupier/git/monaco-languageclient/node_modules/vscode-jsonrpc/lib/main").MessageConnection'.
node-example:   Type 'MessageConnection' is missing the following properties from type 'MessageConnection': onProgress, sendProgress, onUnhandledProgress
node-example: src/json-server.ts(7,8): error TS2613: Module '"/home/apupier/git/monaco-languageclient/node_modules/vscode-uri/lib/umd/index"' has no default export. Did you mean to use 'import { URI } from "/home/apupier/git/monaco-languageclient/node_modules/vscode-uri/lib/umd/index"' instead?
node-example: src/json-server.ts(28,36): error TS2554: Expected 1 arguments, but got 0.
node-example: src/json-server.ts(40,43): error TS7006: Parameter 'change' implicitly has an 'any' type.
node-example: src/json-server.ts(43,35): error TS7006: Parameter 'event' implicitly has an 'any' type.
```

**Comment by RomanNikitenko** [comment]
> hum in fact, seems that compilation errro are nto all reported when there is a previous one, here is a bunch of other:
> 
> ```
> node-example: src/client.ts(66,57): error TS2345: Argument of type 'import("/home/apupier/git/monaco-languageclient/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/main").MessageConnection' is not assignable to parameter of type 'import("/home/apupier/git/monaco-languageclient/node_modules/vscode-jsonrpc/lib/main").MessageConnection'.
> node-example:   Type 'MessageConnection' is missing the following properties from type 'MessageConnection': onProgress, sendProgress, onUnhandledProgress
> node-example: src/json-server.ts(7,8): error TS2613: Module '"/home/apupier/git/monaco-languageclient/node_modules/vscode-uri/lib/umd/index"' has no default export. Did you mean to use 'import { URI } from "/home/apupier/git/monaco-languageclient/node_modules/vscode-uri/lib/umd/index"' instead?
> node-example: src/json-server.ts(28,36): error TS2554: Expected 1 arguments, but got 0.
> node-example: src/json-server.ts(40,43): error TS7006: Parameter 'change' implicitly has an 'any' type.
> node-example: src/json-server.ts(43,35): error TS7006: Parameter 'event' implicitly has an 'any' type.
> ```

I see similar errors in the PR https://github.com/TypeFox/monaco-languageclient/pull/198.
I'm investigating how to fix them.

**Comment by RomanNikitenko** [comment]
@apupier 
Looks like the errors was fixed with your last commit.
Cool!

**Comment by apupier** [comment]
seems https://github.com/TypeFox/monaco-languageclient/pull/199  is more advanced. Closing this PR

**Pull request closed without merging**
