### PR TITLE
Updated to monaco-vscode-api 1.83.3

### PR DESCRIPTION
**Pull request by kaisalmen**
It adds l10n support to the statemachine via different links from index.html for english, german, french and spanish.

@CGNonofr I will update to the final version once [PR #215](https://github.com/CodinGame/monaco-vscode-api/pull/215) is merged.

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr this is now updated to the final version. Any objections to merge this?

**Comment by CGNonofr** [comment]
looks good! except the pipeline that fails

**Comment by kaisalmen** [comment]
@CGNonofr sorry, I just screwed some version up. Will fix this very soon

**Comment by kaisalmen** [comment]
@CGNonofr ready now for real! 😆  ✅

**Pull request merged**
