### PR TITLE
Fix for #357

### PR DESCRIPTION
**Pull request by rubenfiszel**
@CGNonofr I tried to guess how to do an escape hatch but the whole bypassConversion check seems flaky to me. I believe it might make more sense to do a blacklist rather than the current whitelist

### CODE REVIEW

**Comment by CGNonofr** [comment]
Indeed it's not very robust! well spotted, a refactor is probably needed here

**Comment by CGNonofr** [comment]
I did another PR: https://github.com/TypeFox/monaco-languageclient/pull/359

It include some typing to be sure we're only returning a promise when it is expected, what you think?

**Comment by CGNonofr** [comment]
It was fixed by https://github.com/TypeFox/monaco-languageclient/pull/359, thank you very much for your investigations!

**Comment by rubenfiszel** [comment]
Glad to see a clean fix! You use some advanced typing that I'm actually really curious about, will dig into it. Do you plan to do a release soon with your fix ?

**Comment by kaisalmen** [comment]
Et voilà:
https://www.npmjs.com/package/monaco-languageclient/v/1.0.1

**Comment by CGNonofr** [comment]
> Glad to see a clean fix! You use some advanced typing that I'm actually really curious about, will dig into it. 

There is probably a simpler way to do it tho! I don't know why `Exclude`  wasn't working

> Do you plan to do a release soon with your fix ?

I think it will come soon by @kaisalmen

**Comment by rubenfiszel** [comment]
I updated and it did the trick for #356, the dev experience is actually pretty amazing now, thanks a lot!

**Pull request closed without merging**
