### PR TITLE
Update to monaco 0.33 & vscode 1.65

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by CGNonofr** [comment]
@mofux if you're still around here, I'd like you review as well

**Review by mofux — APPROVED** [review]
LGTM 🙏

**Review by kaisalmen — APPROVED** [review]
LGTM and thank you. We could release 0.18.0 this week and afterwards work on enhancements.

**Comment by CGNonofr** [comment]
it looks like there is a CI/travis issue, can you merge it and release the next version @kaisalmen ?

**Comment by kaisalmen** [comment]
Yes, I will merge and produce a release. The CI seems to not working at all. Something for the needs fixing list.

**Comment by kaisalmen** [comment]
@CGNonofr On thing I overlooked. Shouldn't `@types/vscode` and `"engines": { "vscode": "^1.50.0" }` (client) be aligned. I could update and commit this on the master together with CHANGELOG.

**Comment by CGNonofr** [comment]
I admit I have no idea what that `engine` if for

**Comment by CGNonofr** [comment]
you rock

**Comment by CGNonofr** [comment]
btw, what about taking back the `@codingame/monaco-jsonrpc` library as well?

**Comment by kaisalmen** [comment]
Yes, good idea. that's already on the list for [#315](https://github.com/TypeFox/monaco-languageclient/issues/315#issue-1139788779). I was even thinking about putting it as a sub-package in here?

**Comment by CGNonofr** [comment]
By sub-package, do you still mean it will be a separate package on npmjs?

**Pull request merged**
