### PR TITLE
Remove languageId configuration ambiguity

### LINKED ISSUE #779: Typescript with TSX with a language server
## Handling TSX with a language server

Hi. Really love the stuff you guys do and I really love this repo as well as the new improvements.

So. My issue isn't a bug per se, however, I cannot find any resources on this. So I'm basically trying to get the editor to run with TS and the TS language server. So I copied the contents of the `json` folder and set it up to use typescript which seems to be working beautifully and communicates with the language server. So my issue arises when I use a `.tsx` extension, then I get nothing from the language server. I had something similar working with .tsx files about 6 months back, from adapting some of the examples in the repo at the time. Possibly just a small config thing I'm likely missing. Let me know if you'd like a PR for your examples if I manage to sort it out 👍 

*ts language server responding:*
image

Thank you in advance.
Regards

Here's my client code adapted from the json client:

```tsx
/* --------------------------------------------------------------------------------------------
 * Copyright (c) 2024 TypeFox and others.
 * Licensed under the MIT License. See LICENSE in the package root for license information.
 * ------------------------------------------------------------------------------------------ */
import * as monaco from 'monaco-editor';
import getKeybindingsServiceOverride from '@codingame/monaco-vscode-keybindings-service-override';
// this is required syntax highlighting
import '@codingame/monaco-vscode-javascript-default-extension';
import '@codingame/monaco-vscode-typescript-basics-default-extension';
// import '@codingame/monaco-vscode-typescript-language-features-default-extension';
import { LogLevel } from 'vscode/services';
import { MonacoEditorLanguageClientWrapper, WrapperConfig } from 'monaco-editor-wrapper';
import { configureMonacoWorkers } from '../../common/client/utils.js';

monaco.languages.register({
    id: 'typescript',
    extensions: ['.ts', '.tsx'],
    aliases: ['JSON', 'json'],
    mimetypes: ['text/typescript']
});

const text = `
export const X = () => <div/>;
`;

export const buildJsonClientUserConfig = (params: {
    htmlContainer: HTMLElement
}): WrapperConfig => {
    return {
        logLevel: LogLevel.Debug,
        vscodeApiConfig: {
            userServices: {
                ...getKeybindingsServiceOverride(),
            },
            userConfiguration: {
                json: JSON.stringify({
                    'workbench.colorTheme': 'Default Dark Modern',
                    // 'typescript.tsserver.web.projectWideIntellisense.enabled': true,
                    // 'typescript.tsserver.web.projectWideIntellisense.suppressSemanticErrors': false,
                    'diffEditor.renderSideBySide': false,
                    'editor.lightbulb.enabled': 'on',
                    'editor.glyphMargin': true,
                    'editor.guides.bracketPairsHorizontal': true,
                    'editor.experimental.asyncTokenization': true
                })
            }
        },
        editorAppConfig: {
            $type: 'extended',
            codeResources: {
                main: {
                    text,
                    uri: '/xampp2/htdocs/Ethereal/WebStudio2/backend/src/sandbox/src/hello.tsx',
                }
            },
            useDiffEditor: false,
            monacoWorkerFactory: configureMonacoWorkers,
            htmlContainer: params.htmlContainer
        },
        languageClientConfigs: {
            typescript: {
                languageId: 'typescript',
                connection: {
                    options: {
                        $type: 'WebSocketUrl',
                        url: 'ws://localhost:30000/sampleServer',
                        startOptions: {
                            onCall: () => {
                                console.log('Connected to socket.');
                            },
                            reportStatus: true
                        },
                        stopOptions: {
                            onCall: () => {
                                console.log('Disconnected from socket.');
                            },
                            reportStatus: true
                        }
                    }
                }
            }
        }
    };
};

export const runJsonWrapper = () => {
    const wrapper = new MonacoEditorLanguageClientWrapper();

    try {
        document.querySelector('#button-start')?.addEventListener('click', async () => {
            const config = buildJsonClientUserConfig({
                htmlContainer: document.getElementById('monaco-editor-root')!
            });
            await wrapper.initAndStart(config);
        });
        document.querySelector('#button-dispose')?.addEventListener('click', async () => {
            await wrapper.dispose();
        });
    } catch (e) {
        console.error(e);
    }
};

```

### PR DESCRIPTION
**Pull request by kaisalmen**
@RoddoWasHere and @CGNonofr what do you think about a joint type? Is this end-user friendly?

Fixes #779

### CODE REVIEW

**Comment by CGNonofr** [comment]
A document selector can be much more than just the language id, what about allowing the whole DocumentSelector type?

**Comment by kaisalmen** [comment]
> A document selector can be much more than just the language id, what about allowing the whole DocumentSelector type?

True, doesn't it then make sense to completely drop the simple variant and let the uses just directly specify it always? This would be the minimum. WDYT:
```typescript
clientOptions: {
    documentSelector: ['python', 'py']
}
```
Do we need the default `errorHandler` override (see https://github.com/TypeFox/monaco-languageclient/blob/main/packages/wrapper/src/languageClientWrapper.ts#L185-L188)?

**Comment by CGNonofr** [comment]
What about doing something like:
```typescript
            mlcConfig.clientOptions = {
                // disable the default error handler
                errorHandler: {
                    error: () => ({ action: ErrorAction.Continue }),
                    closed: () => ({ action: CloseAction.DoNotRestart })
                },
                ...this.languageClientConfig.clientOptions,
            },
```
?

To keep it by default but letting the user override it

**Comment by kaisalmen** [comment]
> To keep it by default but letting the user override it

@CGNonofr yes, very good idea. Done ⬆️

**Review by CGNonofr — APPROVED** [review]
:+1:

**Comment by kaisalmen** [comment]
@CGNonofr configuration has become slightly more complex, but it is now clearer and less magic things happen.

**Comment by cdietrich** [comment]
@kaisalmen with that change our stuff does no longer work
how does the document selector and the contributes.languages relate
(am not sure if this is the issue or something changes in next7

**Comment by kaisalmen** [comment]
@cdietrich the `codeUri` has to match the document selector, see python example https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/python/client/main.ts#L35 and https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/python/client/config.ts#L55 or see how it is done with `fileExt` in https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/langium/statemachine/config/wrapperStatemachineConfig.ts

**Comment by kaisalmen** [comment]
@cdietrich we have [this](https://github.com/TypeFox/monaco-languageclient/discussions/773) for future ideas.

Currently there is no Milestone or something similar. I am likely not done with breaking changes. There should be a final release before end of the month.

**Comment by RoddoWasHere** [comment]
Hi @kaisalmen. Apologies. I have been a bit busy. Concerning this issue I raised [#779](https://github.com/TypeFox/monaco-languageclient/issues/779) this helps a ton. Sorted out my issue with using the same lang client for 'typescript' and 'typescriptreact'.
Thanks a ton for the help 👍 😃

**Pull request merged**
