### PR TITLE
Update to monaco 0.34/vscode 1.69

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Review by kaisalmen — APPROVED** [review]
LGTM. I just released 0.34.0 of monaco-editor-workers and therefore pushed an update.

**Comment by kaisalmen** [comment]
Pushed the lock file.

**Comment by CGNonofr** [comment]
Thanks! note that monaco-vscode-api is ONLY compatible with monaco 0.34 therefore I think any monaco-languageclient update of monacy-editor should be a major release

**Comment by kaisalmen** [comment]
Yes, I was thinking the same thing. 3.0.0 shall it be! I will prepare the release.

Thank you for your work! I saw the service additions in monaco-vsocde-api.

**Comment by kaisalmen** [comment]
I have pushed another update with some changes to the README and CHANGELOG.
I tested it locally and it looks good.
If you think, we are good to go, please presse the merge button, then I will produce the release.

**Comment by CGNonofr** [comment]
FYI, monaco-vscode-api was designed at first to only provide the programmatic VSCode api, but it evolved and now provide a way to use the declarative VSCode API (the things declared in the package.json of extensions)

I created a demo: https://github.com/CodinGame/monaco-vscode-api/pull/39

**Comment by kaisalmen** [comment]
Forgot to write: The made the release yesterday

**Pull request merged**
