### PR TITLE
Bump monaco version

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Bump Monaco to 0.19.3

I created the branch based on https://github.com/TypeFox/monaco-languageclient/pull/198 and tried to fix the compilation errors.

### CODE REVIEW

**Comment by akosyakov** [comment]
@RomanNikitenko ping me if you have any Qs

**Comment by akosyakov** [comment]
@RomanNikitenko we need a new version of vscode-ws-jsonrpc then with 5.0.0

**Comment by akosyakov** [comment]
@RomanNikitenko published vscode-ws-jsonrpc@0.2.0, you should be able to use it now

**Comment by akosyakov** [comment]
@RomanNikitenko Let me know if you need any other support. Usually we will do a dev release from the PR, open a PR for Theia against dev version and test it there.

**Comment by RomanNikitenko** [comment]
@akosyakov 
About `dev release` - is it OK if within testing dev version I find something that we have to fix in `monaco-languageclient` repo and prepare another dev version? 

I could test it locally first: add for `theia` repo dependency on these changes like:
`"monaco-languageclient": "file:../../../monaco-languageclient/client",`

Also for testing it for `theia` repo I need:
 > Upgrade TypeFox/monaco-editor-core to the latest Microsoft/monaco-editor-core

**Comment by akosyakov** [comment]
> About dev release - is it OK if within testing dev version I find something that we have to fix in monaco-languageclient repo and prepare another dev version

@RomanNikitenko yes, that's an idea. I will publish it today then?

> Upgrade TypeFox/monaco-editor-core to the latest Microsoft/monaco-editor-core

I will do it for you today.

**Comment by RomanNikitenko** [comment]
@akosyakov 
>@RomanNikitenko yes, that's an idea. I will publish it today then?

I would like to pick up the changes from the PR https://github.com/TypeFox/monaco-languageclient/pull/191 to have ability to test them as well on dev version for `theia`.
WDYT?

If you don't mind I can merge the changes from the specified PR to my draft PR.

**Comment by akosyakov** [comment]
@RomanNikitenko yes, it is fine

**Comment by RomanNikitenko** [comment]
@akosyakov 
I merged the specified PR changes to the current PR.

**Comment by akosyakov** [comment]
there going to be Monaco 0.20 soon 🙈 https://github.com/microsoft/vscode/tree/standalone/0.20.x

Should we rather go for it instead?

**Comment by akosyakov** [comment]
Let's stick with 0.19.

**Comment by akosyakov** [comment]
Published dev tag from this branch:
> Successfully published:
> - monaco-languageclient@0.11.1-dev.4+6590ed7

Published 0.19.3 monaco from https://github.com/theia-ide/vscode/tree/standalone/0.19.x
> + @theia/monaco-editor-core@0.19.3

**Comment by RomanNikitenko** [comment]
@akosyakov 
thank you very much!

I'll apply these versions for `theia` repo and prepare the corresponding PR for testing.

**Comment by akosyakov** [comment]
@RomanNikitenko just open it is as a draft, we can collaborate on it, i.e. i can help writing integration tests  while you are fixing others :) more of such we have less work it would be to migrate next time

**Comment by CGNonofr** [comment]
It seems we have an issue in the vscode-compatibility (vscode-api.ts): the `workspaceFolders` getter returns a new list containing a new Uri every time.

The consequence is that a DidChangeWorkspaceFoldersNotification is sent at startup, with an identical `added` and `removed` (same Uri but a different instance) and some LSP implementations don't like that at all!

**Comment by akosyakov** [comment]
@RomanNikitenko I want to merge it and make a new release. Could you open for a review it please?

**Pull request merged**
