### PR TITLE
Run language clients independent of wrapper lifecycle

### PR DESCRIPTION
**Pull request by kaisalmen**
The vscode api init can now be run independent of the wrapper init.

## Changes:

Examples:
- Two language clients example can now be launch with both language clients initialized by the wrapper or externally.

`monaco-languageclient`:
  - API and internal functions clean-up

`monaco-editor-wrapper`:
  - API and internal functions clean-up
  - Re-combination of `EditorAppClassic` and `EditorAppClassic`
  - Moved `$type` to mandatory top-level element in `WrapperConfig`
  - Reduced minimally mandatory configuration
  - Exposed vscodeApi init functions

`@typefox/monaco-editor-react`:
  - Internal functions clean-up. `containerRef.current` is directly passed to editor start.

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr I will update to monaco-vscode-api@11.1.1 before merge. This is now ready for review

**Comment by kaisalmen** [comment]
@CGNonofr oh sorry, will set it back to draft. The description and CHANGELOGs are not updated

**Comment by kaisalmen** [comment]
@CGNonofr I needed to add `"@codingame/monaco-vscode-chat-extensions-notebook-task-terminal-testing-common": "~11.1.1"` to fix the tests? Any idea what is wrong, see here:
https://github.com/TypeFox/monaco-languageclient/actions/runs/11957175236/job/33333682939

**Comment by CGNonofr** [comment]
Yes, there are currently issues with inter-package, I'll investigate as soon as I got time

**Comment by kaisalmen** [comment]
@CGNonofr sounds good. The issue is not blocking the PR.

**Review by CGNonofr — APPROVED** [review]
Very complicated MR to review :thinking: I've tried to spot bad things but the review was pretty superficial

**Comment by kaisalmen** [comment]
> Very complicated MR to review 🤔 I've tried to spot bad things but the review was pretty superficial

Yes, sorry, it's a lot of internal clean-up / condensation. I am really thinking if the package(s) should be renamed, because they are more becoming monaco-vscode-api wrapper than a monaco-editor-wrapper

**Pull request merged**
